-- AULACONECTA: PANEL DE CIBERSEGURIDAD (solo administradores)
-- Ejecutar completo en Supabase SQL Editor.

create table if not exists public.security_scan_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references public.profiles(id) on delete cascade,
  score integer not null check (score between 0 and 100),
  checks jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists security_scan_logs_created_at_idx
  on public.security_scan_logs (created_at desc);

create index if not exists security_scan_logs_admin_id_idx
  on public.security_scan_logs (admin_id);

alter table public.security_scan_logs enable row level security;

revoke all on table public.security_scan_logs from anon;
revoke all on table public.security_scan_logs from authenticated;

drop policy if exists security_scan_logs_admin_select on public.security_scan_logs;
create policy security_scan_logs_admin_select
on public.security_scan_logs
for select
to authenticated
using (public.current_user_is_admin());

create or replace function public.admin_record_security_scan(
  scan_score integer,
  scan_checks jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  new_id bigint;
begin
  if not public.current_user_is_admin() then
    raise exception 'Solo los administradores pueden registrar análisis de seguridad.';
  end if;

  if scan_score < 0 or scan_score > 100 then
    raise exception 'La puntuación debe estar entre 0 y 100.';
  end if;

  insert into public.security_scan_logs (admin_id, score, checks)
  values (auth.uid(), scan_score, coalesce(scan_checks, '{}'::jsonb))
  returning id into new_id;

  return new_id;
end;
$$;

revoke all on function public.admin_record_security_scan(integer, jsonb) from public;
grant execute on function public.admin_record_security_scan(integer, jsonb) to authenticated;

create or replace function public.admin_security_overview()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_catalog, storage
as $$
declare
  total_tables integer;
  tables_with_rls integer;
  policy_count integer;
  tables_without_rls jsonb;
  public_buckets jsonb;
  security_definer_functions integer;
  pending_reports integer;
  suspended_users integer;
  recent_scans jsonb;
begin
  if not public.current_user_is_admin() then
    raise exception 'Solo los administradores pueden consultar el diagnóstico de seguridad.';
  end if;

  select count(*)::integer,
         count(*) filter (where c.relrowsecurity)::integer
  into total_tables, tables_with_rls
  from pg_catalog.pg_class c
  join pg_catalog.pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relkind = 'r'
    and c.relname not like 'pg_%';

  select count(*)::integer
  into policy_count
  from pg_catalog.pg_policies
  where schemaname = 'public';

  select coalesce(jsonb_agg(c.relname order by c.relname), '[]'::jsonb)
  into tables_without_rls
  from pg_catalog.pg_class c
  join pg_catalog.pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relkind = 'r'
    and not c.relrowsecurity
    and c.relname not like 'pg_%';

  select coalesce(jsonb_agg(b.id order by b.id), '[]'::jsonb)
  into public_buckets
  from storage.buckets b
  where b.public is true;

  select count(*)::integer
  into security_definer_functions
  from pg_catalog.pg_proc p
  join pg_catalog.pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and p.prosecdef is true;

  select count(*)::integer
  into pending_reports
  from public.reports
  where status = 'pending';

  select count(*)::integer
  into suspended_users
  from public.profiles
  where account_status = 'suspended';

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', scan.id,
        'score', scan.score,
        'created_at', scan.created_at
      ) order by scan.created_at desc
    ),
    '[]'::jsonb
  )
  into recent_scans
  from (
    select id, score, created_at
    from public.security_scan_logs
    order by created_at desc
    limit 10
  ) scan;

  return jsonb_build_object(
    'checked_at', now(),
    'authorization', jsonb_build_object(
      'strict_admin', true,
      'admin_id', auth.uid()
    ),
    'rls', jsonb_build_object(
      'total_tables', total_tables,
      'tables_with_rls', tables_with_rls,
      'policy_count', policy_count,
      'tables_without_rls', tables_without_rls
    ),
    'storage', jsonb_build_object(
      'public_buckets', public_buckets
    ),
    'database', jsonb_build_object(
      'security_definer_functions', security_definer_functions
    ),
    'activity', jsonb_build_object(
      'pending_reports', pending_reports,
      'suspended_users', suspended_users
    ),
    'recent_scans', recent_scans
  );
end;
$$;

revoke all on function public.admin_security_overview() from public;
grant execute on function public.admin_security_overview() to authenticated;
