-- ============================================================
-- AULACONECTA - FAVORITOS DE MATERIALES
-- Ejecutar una sola vez en Supabase > SQL Editor
-- ============================================================

create table if not exists public.material_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  material_id bigint not null references public.materials(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint material_favorites_user_material_unique unique (user_id, material_id)
);

create index if not exists material_favorites_user_id_idx
  on public.material_favorites(user_id);

create index if not exists material_favorites_material_id_idx
  on public.material_favorites(material_id);

alter table public.material_favorites enable row level security;

drop policy if exists "Users can view their material favorites"
  on public.material_favorites;
create policy "Users can view their material favorites"
  on public.material_favorites
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can create their material favorites"
  on public.material_favorites;
create policy "Users can create their material favorites"
  on public.material_favorites
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their material favorites"
  on public.material_favorites;
create policy "Users can delete their material favorites"
  on public.material_favorites
  for delete
  to authenticated
  using (auth.uid() = user_id);
