-- AulaConecta: gamificación, logros y ranking
-- Ejecutar completo en Supabase > SQL Editor.

create table if not exists public.user_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  achievement_key text not null,
  unlocked_at timestamptz not null default now(),
  unique (user_id, achievement_key)
);

alter table public.user_achievements enable row level security;

drop policy if exists "Users can read achievements" on public.user_achievements;
create policy "Users can read achievements"
on public.user_achievements for select
to authenticated
using (true);

drop policy if exists "Users can unlock own achievements" on public.user_achievements;
create policy "Users can unlock own achievements"
on public.user_achievements for insert
to authenticated
with check (auth.uid() = user_id);

create or replace function public.calculate_user_xp(target_user uuid)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select
    coalesce((select count(*) * 30 from public.tutoring_sessions where tutor_id = target_user and status = 'completed'), 0)::int +
    coalesce((select count(*) * 35 from public.materials where user_id = target_user and review_status = 'approved' and is_active = true), 0)::int +
    coalesce((select count(*) * 10 from public.study_groups where creator_id = target_user), 0)::int +
    coalesce((select count(*) * 25 from public.reviews where reviewed_user_id = target_user and rating = 5), 0)::int;
$$;

create or replace function public.get_my_gamification()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  xp integer;
  completed_tutoring integer;
  approved_materials integer;
  created_groups integer;
  five_star_reviews integer;
  review_count integer;
  average_rating numeric;
begin
  if uid is null then raise exception 'No authenticated user'; end if;

  select count(*) into completed_tutoring from tutoring_sessions where tutor_id = uid and status = 'completed';
  select count(*) into approved_materials from materials where user_id = uid and review_status = 'approved' and is_active = true;
  select count(*) into created_groups from study_groups where creator_id = uid;
  select count(*) into five_star_reviews from reviews where reviewed_user_id = uid and rating = 5;
  select count(*), coalesce(avg(rating), 0) into review_count, average_rating from reviews where reviewed_user_id = uid;
  xp := public.calculate_user_xp(uid);

  return jsonb_build_object(
    'xp', xp,
    'completed_tutoring', completed_tutoring,
    'approved_materials', approved_materials,
    'created_groups', created_groups,
    'five_star_reviews', five_star_reviews,
    'review_count', review_count,
    'average_rating', round(average_rating, 2)
  );
end;
$$;

create or replace function public.get_gamification_leaderboard(result_limit integer default 20)
returns table (
  user_id uuid,
  first_name text,
  last_name text,
  avatar_url text,
  xp integer
)
language sql
stable
security definer
set search_path = public
as $$
  select p.id, p.first_name, p.last_name, p.avatar_url,
         public.calculate_user_xp(p.id) as xp
  from public.profiles p
  order by xp desc, p.first_name asc
  limit greatest(1, least(result_limit, 100));
$$;

grant execute on function public.calculate_user_xp(uuid) to authenticated;
grant execute on function public.get_my_gamification() to authenticated;
grant execute on function public.get_gamification_leaderboard(integer) to authenticated;
