-- Ejecutar después del SQL base, o usar el SQL base actualizado incluido en el ZIP.
begin;


-- ------------------------------------------------------------
-- 12. ROLES, AUDITORÍA Y ADMINISTRACIÓN SEGURA
-- ------------------------------------------------------------
alter table public.profiles add column if not exists role text not null default 'student';
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('student','moderator','admin'));
update public.profiles set role='admin' where is_admin=true and role<>'admin';
update public.profiles set is_admin=(role='admin') where is_admin is distinct from (role='admin');

create or replace function public.current_user_role()
returns text language sql stable security definer set search_path=public
as $$ select coalesce((select role from public.profiles where id=auth.uid()), 'student'); $$;

create or replace function public.current_user_is_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select coalesce((select role='admin' or is_admin from public.profiles where id=auth.uid()), false); $$;

create or replace function public.current_user_can_moderate()
returns boolean language sql stable security definer set search_path=public
as $$ select coalesce((select role in ('admin','moderator') or is_admin from public.profiles where id=auth.uid()), false); $$;

grant execute on function public.current_user_role() to authenticated;
grant execute on function public.current_user_is_admin() to authenticated;
grant execute on function public.current_user_can_moderate() to authenticated;

-- Impide que un estudiante se otorgue privilegios actualizando su propio perfil.
revoke update on public.profiles from authenticated;
grant update(first_name,last_name,career_id,semester_id,avatar_url,bio,updated_at) on public.profiles to authenticated;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.audit_logs enable row level security;
drop policy if exists audit_logs_admin_read on public.audit_logs;
create policy audit_logs_admin_read on public.audit_logs for select to authenticated using (public.current_user_can_moderate());
revoke insert, update, delete on public.audit_logs from authenticated;
create index if not exists audit_logs_created_idx on public.audit_logs(created_at desc);
create index if not exists audit_logs_actor_idx on public.audit_logs(actor_id,created_at desc);

create or replace function public.write_audit_log(
  target_action text,
  target_entity_type text,
  target_entity_id text default null,
  target_reason text default null,
  target_metadata jsonb default '{}'::jsonb
) returns void language plpgsql security definer set search_path=public
as $$
begin
  insert into public.audit_logs(actor_id,action,entity_type,entity_id,reason,metadata)
  values(auth.uid(),target_action,target_entity_type,target_entity_id,target_reason,coalesce(target_metadata,'{}'::jsonb));
end; $$;
revoke all on function public.write_audit_log(text,text,text,text,jsonb) from public;

create or replace function public.admin_set_user_role(target_user_id uuid, new_role text)
returns jsonb language plpgsql security definer set search_path=public
as $$
begin
  if not public.current_user_is_admin() then raise exception 'Solo un administrador puede cambiar roles.' using errcode='42501'; end if;
  if new_role not in ('student','moderator','admin') then raise exception 'Rol no válido.'; end if;
  if target_user_id=auth.uid() and new_role<>'admin' then raise exception 'No puedes retirar tu propio rol administrativo.'; end if;
  update public.profiles set role=new_role,is_admin=(new_role='admin'),updated_at=now() where id=target_user_id;
  if not found then raise exception 'El usuario no existe.'; end if;
  perform public.write_audit_log('role_changed','profile',target_user_id::text,null,jsonb_build_object('role',new_role));
  return jsonb_build_object('user_id',target_user_id,'role',new_role);
end; $$;

create or replace function public.admin_delete_request(target_id bigint, target_reason text default null)
returns boolean language plpgsql security definer set search_path=public
as $$
begin
  if not public.current_user_is_admin() then raise exception 'Solo un administrador puede eliminar solicitudes.' using errcode='42501'; end if;
  delete from public.tutoring_sessions where request_id=target_id;
  delete from public.tutor_applications where request_id=target_id;
  delete from public.tutor_requests where id=target_id;
  if not found then raise exception 'La solicitud no existe.'; end if;
  perform public.write_audit_log('deleted','tutor_request',target_id::text,target_reason);
  return true;
end; $$;

create or replace function public.admin_delete_group(target_id bigint, target_reason text default null)
returns boolean language plpgsql security definer set search_path=public
as $$
begin
  if not public.current_user_is_admin() then raise exception 'Solo un administrador puede eliminar grupos.' using errcode='42501'; end if;
  delete from public.group_members where group_id=target_id;
  delete from public.study_groups where id=target_id;
  if not found then raise exception 'El grupo no existe.'; end if;
  perform public.write_audit_log('deleted','study_group',target_id::text,target_reason);
  return true;
end; $$;

create or replace function public.admin_delete_material(target_id bigint, target_reason text default null)
returns text language plpgsql security definer set search_path=public
as $$
declare path text;
begin
  if not public.current_user_can_moderate() then raise exception 'No tienes permiso para eliminar materiales.' using errcode='42501'; end if;
  select file_path into path from public.materials where id=target_id for update;
  if not found then raise exception 'El material no existe.'; end if;
  delete from public.material_favorites where material_id=target_id;
  delete from public.materials where id=target_id;
  perform public.write_audit_log('deleted','material',target_id::text,target_reason,jsonb_build_object('file_path',path));
  return path;
end; $$;

create or replace function public.admin_cancel_session(target_id bigint, target_reason text default null)
returns boolean language plpgsql security definer set search_path=public
as $$
begin
  if not public.current_user_is_admin() then raise exception 'Solo un administrador puede cancelar tutorías.' using errcode='42501'; end if;
  update public.tutoring_sessions set status='cancelled',updated_at=now() where id=target_id and status not in ('completed','cancelled');
  if not found then raise exception 'La tutoría no existe o ya está cerrada.'; end if;
  perform public.write_audit_log('cancelled','tutoring_session',target_id::text,target_reason);
  return true;
end; $$;

revoke all on function public.admin_set_user_role(uuid,text) from public;
revoke all on function public.admin_delete_request(bigint,text) from public;
revoke all on function public.admin_delete_group(bigint,text) from public;
revoke all on function public.admin_delete_material(bigint,text) from public;
revoke all on function public.admin_cancel_session(bigint,text) from public;
grant execute on function public.admin_set_user_role(uuid,text) to authenticated;
grant execute on function public.admin_delete_request(bigint,text) to authenticated;
grant execute on function public.admin_delete_group(bigint,text) to authenticated;
grant execute on function public.admin_delete_material(bigint,text) to authenticated;
grant execute on function public.admin_cancel_session(bigint,text) to authenticated;

-- Moderadores y administradores pueden revisar materiales; solo admin gestiona el resto.
drop policy if exists materials_update_own_admin on public.materials;
create policy materials_update_own_admin on public.materials for update to authenticated
using (user_id=auth.uid() or public.current_user_can_moderate())
with check (user_id=auth.uid() or public.current_user_can_moderate());
drop policy if exists materials_delete_own_admin on public.materials;
create policy materials_delete_own_admin on public.materials for delete to authenticated
using (user_id=auth.uid() or public.current_user_can_moderate());

drop policy if exists materials_owner_delete on storage.objects;
create policy materials_owner_delete on storage.objects for delete to authenticated
using(bucket_id='materials' and ((storage.foldername(name))[1]=auth.uid()::text or public.current_user_can_moderate()));


commit;

-- Convierte tu cuenta en administradora (cambia el correo):
-- update public.profiles p set role='admin',is_admin=true from auth.users u where p.id=u.id and u.email='TU_CORREO@EJEMPLO.COM';
