begin;
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  entity_type text not null check (entity_type in ('material','request','group','profile','tutoring_session')),
  entity_id text not null,
  reason text not null check (reason in ('spam','inappropriate','misleading','harassment','copyright','other')),
  details text check (details is null or char_length(details)<=1000),
  status text not null default 'pending' check (status in ('pending','resolved','dismissed')),
  resolution text,
  resolved_by uuid references public.profiles(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists reports_unique_pending_idx on public.reports(reporter_id,entity_type,entity_id) where status='pending';
create index if not exists reports_status_created_idx on public.reports(status,created_at desc);
alter table public.reports enable row level security;
drop policy if exists reports_insert_own on public.reports;
create policy reports_insert_own on public.reports for insert to authenticated with check (reporter_id=auth.uid() and status='pending' and resolved_by is null and resolved_at is null);
drop policy if exists reports_read_own_or_moderator on public.reports;
create policy reports_read_own_or_moderator on public.reports for select to authenticated using (reporter_id=auth.uid() or public.current_user_can_moderate());
revoke update,delete on public.reports from authenticated;
grant select,insert on public.reports to authenticated;
create or replace function public.admin_resolve_report(target_report_id bigint,target_status text,target_resolution text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare result public.reports;
begin
 if not public.current_user_can_moderate() then raise exception 'No tienes permiso para gestionar reportes.' using errcode='42501'; end if;
 if target_status not in ('resolved','dismissed') then raise exception 'Estado de resolución no válido.'; end if;
 update public.reports set status=target_status,resolution=nullif(trim(target_resolution),''),resolved_by=auth.uid(),resolved_at=now(),updated_at=now() where id=target_report_id and status='pending' returning * into result;
 if not found then raise exception 'El reporte no existe o ya fue procesado.'; end if;
 perform public.write_audit_log('report_'||target_status,'report',target_report_id::text,target_resolution,jsonb_build_object('entity_type',result.entity_type,'entity_id',result.entity_id));
 return jsonb_build_object('id',result.id,'status',result.status);
end;$$;
revoke all on function public.admin_resolve_report(bigint,text,text) from public;
grant execute on function public.admin_resolve_report(bigint,text,text) to authenticated;
commit;
